### ISSUE TITLE
请问这个插件可以使用吗

### ISSUE THREAD

**Issue by ClearSeve** [Redwinam/obsidian-typecho#1]

**Comment by Redwinam** [comment]
目前还有一些bug，推送过去的内容会被放在草稿箱里，不会直接发布。目前用的Typecho默认XML的接口，在考虑后续换用Typecho插件Restful-API的接口，不过最近有点忙~等空下来！

**Comment by ClearSeve** [comment]
谢谢, 那我使用一下
